# Generated by Django 4.0 on 2021-12-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django101', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='home_town',
            field=models.CharField(default='Sofia', max_length=25),
            preserve_default=False,
        ),
    ]
